name: CHIP-8 Emulator CI
on: [push]
jobs:
  run-cargo-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t chip8
      - name: Commit production build
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Committed production build'
